name: CD - Deploy

on:
  push:
    branches: [release]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Login to Public ECR
        run: aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws

      - name: Build Docker image
        run: |
          docker build -t ${{ vars.ECR_REPOSITORY_URI }}:latest .
          docker tag ${{ vars.ECR_REPOSITORY_URI }}:latest ${{ vars.ECR_REPOSITORY_URI }}:${{ github.sha }}

      - name: Push Docker image
        run: |
          docker push ${{ vars.ECR_REPOSITORY_URI }}:latest
          docker push ${{ vars.ECR_REPOSITORY_URI }}:${{ github.sha }}

      - name: Register new task definition
        id: task-def
        run: |
          task_def=$(aws ecs describe-task-definition --task-definition ${{ vars.ECS_TASK_DEFINITION }})
          new_def=$(echo $task_def | jq --arg IMAGE "${{ vars.ECR_REPOSITORY_URI }}:${{ github.sha }}" '.taskDefinition | .containerDefinitions[0].image = $IMAGE | {family, containerDefinitions: [.containerDefinitions[0]], executionRoleArn, networkMode, requiresCompatibilities, cpu, memory}')
          echo "$new_def" > new-task-def.json
          aws ecs register-task-definition --cli-input-json file://new-task-def.json

      - name: Update ECS service
        run: |
          aws ecs update-service \
            --cluster ${{ vars.ECS_CLUSTER }} \
            --service ${{ vars.ECS_SERVICE }} \
            --task-definition ${{ vars.ECS_TASK_DEFINITION }} \
            --desired-count 1